# Generated by Django 4.2.1 on 2023-10-10 01:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_usermodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['Name']},
        ),
        migrations.AlterModelOptions(
            name='usermodel',
            options={'ordering': ['Date', 'Time']},
        ),
        migrations.AddField(
            model_name='usermodel',
            name='Ticket_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
