# Generated by Django 4.2.1 on 2023-10-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_movie_options_alter_usermodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Image',
            field=models.TextField(max_length=900),
        ),
    ]
