# Generated by Django 4.2.1 on 2023-10-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Image',
            field=models.CharField(max_length=250),
        ),
    ]
