# Generated by Django 4.2.1 on 2023-10-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_usermodel_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='Token',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='User_name',
            field=models.CharField(default='no name', max_length=100),
        ),
    ]
